/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.search-result[_ngcontent-%COMP%]{\r\n  border-bottom: 1px solid gray;\r\n  border-left: 1px solid gray;\r\n  border-right: 1px solid gray;\r\n  width:195px;\r\n  height: 16px;\r\n  padding: 5px;\r\n  background-color: white;\r\n  cursor: pointer;\r\n}\r\n\r\n.search-result[_ngcontent-%COMP%]:hover {\r\n  color: #eee;\r\n  background-color: #607D8B;\r\n}\r\n\r\n#search-box[_ngcontent-%COMP%]{\r\n  width: 200px;\r\n  height: 20px;\r\n}'];
//# sourceMappingURL=hero-search.component.css.shim.ngstyle.js.map